/******************************************************************************
*  Generated by PSoC Designer 5.4.2946
******************************************************************************/
// =============================================================================
// FILENAME: PSoCAPI.h
// 
// Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
// 
// NOTES:
// Do not modify this file. It is generated by PSoC Designer each time the
// generate application function is run. The values of the parameters in this
// file can be modified by changing the values of the global parameters in the
// device editor.
// 
// =============================================================================
 
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "Counter16_Tick.h"
#include "PWM8_LeftFwd.h"
#include "PWM8_LeftRev.h"
#include "PWM8_Pump.h"
#include "PWM8_RightFwd.h"
#include "PWM8_RightRev.h"
#include "SAR10.h"
#include "SleepTimer.h"
#include "TX8_BT.h"

#endif
